name: peanut
version: 4.1.2-dev
description: >-
  Update your GitHub gh-pages branch with the compiled output of your Dart web
  app. Supports 'pub build' and the new 'pub run build_runner'.
repository: https://github.com/kevmoo/peanut.dart
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.0.0
  checked_yaml: ^2.0.0
  git: ^2.0.0
  glob: ^2.0.0
  io: ^1.0.0
  json_annotation: ^4.3.0
  meta: ^1.0.0
  path: ^1.3.4
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_cli: ^2.1.1
  build_runner: ^2.0.1
  build_verify: ^2.0.0
  build_version: ^2.0.0

  # build_web_compilers is here to support the `example` dir
  build_web_compilers: ^3.0.0

  json_serializable: ^6.0.0
  lints: ^1.0.0
  # Needed because we are configuring `combining_builder`
  source_gen: ^1.0.0
  test: ^1.6.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

executables:
  peanut: peanut
